# Generated by Django 4.2.15 on 2024-08-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kind_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GratitudeEntry',
        ),
    ]
