# Generated by Django 4.2.15 on 2024-08-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kind_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gratitudeentry',
            options={'verbose_name': 'Gratitude Entry', 'verbose_name_plural': 'Gratitude Entries'},
        ),
    ]
