# Generated by Django 4.2.15 on 2024-09-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kind_app', '0005_rename_entry_id_gratitudeentry_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gratitudeentry',
            old_name='user_id',
            new_name='user',
        ),
    ]
