# Generated by Django 4.2.15 on 2025-06-04 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kind_app', '0008_moodlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satisfaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('satisfaction', models.CharField(choices=[('very content', 'Very Content'), ('content', 'Content'), ('neutral', 'Neutral'), ('unhappy', 'Unhappy'), ('very unhappy', 'Very Unhappy')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Satisfaction Log',
                'verbose_name_plural': 'Satisfaction Logs',
            },
        ),
        migrations.DeleteModel(
            name='MoodLog',
        ),
    ]
