# Generated by Django 4.2.15 on 2025-06-04 14:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kind_app', '0009_satisfaction_delete_moodlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GratitudeEntry',
            new_name='Kudos',
        ),
        migrations.AlterModelOptions(
            name='kudos',
            options={'verbose_name': 'Kudos Entry', 'verbose_name_plural': 'Kudos Entries'},
        ),
    ]
