# Generated by Django 4.2.15 on 2025-06-04 15:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kind_app', '0010_rename_gratitudeentry_kudos_alter_kudos_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KindAct',
            new_name='Achievement',
        ),
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Achievement', 'verbose_name_plural': 'Achievement'},
        ),
    ]
