# Generated by Django 4.2.15 on 2024-09-02 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kind_app', '0004_alter_gratitudeentry_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gratitudeentry',
            old_name='entry_id',
            new_name='id',
        ),
    ]
