# For setting up automated checks in github actions (describes checks before merging to main)
name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.9", "3.10"]
    env: 
      SECRET_KEY: "test-key"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
    - name: Run Coverage
      run: |
        coverage run manage.py test
        coverage report --omit=manage.py,kind/settings.py --fail-under=100
    - name: Run Bandit scan
      run: |
        bandit -r . -x ./kind_app/tests.py
    - name: Run Safety scan
      run: |
        safety check --full-report